markdown: kramdown
#markdown: rdiscount
permalink: /:year/:month/:day/:title.html
url: http://blog.fungenomics.com
name: "Fungenomics"
author: "YellowTree"
highlighter: pygments
safe: true
paginate: 16
auto: true
