#markdown: rdiscount
markdown: kramdown
permalink: /:year/:month/:day/:title.html
url: http://www.stbioinf.com
name: "STbioinf"
author: "YellowTree"
highlighter: pygments
safe: true
paginate: 16
auto: true
