markdown: kramdown
#markdown: rdiscount
permalink: /:year/:month/:day/:title.html
url: http://stbioinf.com
name: "STbioinf"
author: "YellowTree"
highlighter: pygments
safe: true
paginate: 16
auto: true
